/* autogenerated by Processing revision 1276 on 2021-10-20 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.net.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Board extends PApplet {



Server serv;
final int port = 2000;


final int w = 96;
final int h = 64;
final int dot_size = 10;
final int part_dist = 3;
final float offset = dot_size / 2;

final int wind_W = w * dot_size + (w-1) * dot_size/part_dist;
final int wind_H = h * dot_size + (h-1) * dot_size/part_dist;

int filling[][] = new int[w][h];

 public void setup() {
  surface.setSize(wind_W, wind_H);
  surface.setLocation(displayWidth-wind_W-10, 0);
  noStroke();
  /****************************************/
  serv = new Server(this, port);
  println(wind_W, wind_H);
  println(displayWidth, displayHeight);
}

 public void draw() {
  background(200);
  for (int j = 0; j < h; j++)
    for (int i = 0; i < w; i++) {
      servUpdate();
      fill(filling[i][j]);
      circle(i*dot_size*(1 + 1f / part_dist)+offset, j*dot_size*(1 + 1f / part_dist)+offset, dot_size);
    }
}


 public void servUpdate() {
  Client cl = serv.available();
  if (cl != null && cl.available() > 0) {
    String resp = cl.readStringUntil('\n');
    if (resp != null) {
      String[] splstr = split(resp.trim(), ' ');
      printArray(splstr);
      int x, y, fl;
      try{
        x = PApplet.parseInt(splstr[0]);
        y = PApplet.parseInt(splstr[1]);
        fl = PApplet.parseInt(splstr[2]);
      }
      catch(Exception ex){
        println("Exception: ", ex.getMessage());
        return;
      }
      if (x > w-1 || x < 0 || y > h-1 || y < 0)
        return;
      filling[x][y] = fl;
    }
  }
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Board" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
